accounts/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    
    path('signup_success/', views.SignUpSuccess.as_view(), name='signup_success'),
    
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    
    
    
]

proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        
    path('', include('schedule.urls')),
    
    path('', include('accounts.urls')),
    
    
]

schedule/urls.py
from django.urls import path

from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

    path('index2/', views.Index2.as_view(), name='index2'),
    
    path('register/', views.CreateSchedule.as_view(), name='register'),
    
    path('done/', views.Done.as_view(), name='done'),

    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),

    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),

    path('contact/', views.Contact.as_view(), name='contact'),
    
    
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

schedule/models.py
from django.db import models

from accounts.models import CustomUser

class ScheduleRegister(models.Model):
    
    user = models.ForeignKey(
        CustomUser,
        verbose_name='user',
        on_delete=models.CASCADE
    )
    
    date = models.DateField(
        verbose_name='date'
    )
    
    event = models.TextField(
        verbose_name='event'
    )
    
    place = models.CharField(
        verbose_name='place',
        max_length=200
    )

    
    def __str__(self):
        return self.event
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        
        fields = ('username', 'email', 'password1', 'password2')

schedule/forms.py
from django.forms import ModelForm, DateInput, Form, CharField, EmailField, Textarea

from .models import ScheduleRegister

class DateInput(DateInput):
    
    input_type = 'date'
    
class ScheduleRegisterForm(ModelForm):  
    class Meta:
        
        model = ScheduleRegister
        
        fields = ['date', 'event', 'place']
        
        widgets = {
            'date': DateInput(),
            }


class ContactForm(Form):
    name = CharField(label='お名前')
    email = EmailField(label='メールアドレス')
    title = CharField(label='件名')
    message = CharField(label='メッセージ', widget=Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = 'お名前'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = '件名'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージ'
        self.fields['message'].widget.attrs['class'] = 'form-control'

    

accounts/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render

from django.views import generic

from .forms import CustomUserCreationForm

from django.urls import reverse_lazy

class SignUp(generic.CreateView):
    
    template_name = 'signup.html'
    
    form_class = CustomUserCreationForm
    
    success_url = reverse_lazy('accounts:signup_success')
    
    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccess(generic.TemplateView):
    
    template_name ='signup_success.html'    

schedule/views.py
from django.shortcuts import render

from django.views import generic

from django.urls import reverse_lazy

from .forms import ScheduleRegisterForm, ContactForm

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required

from .models import ScheduleRegister

from django.contrib import messages

from django.core.mail import EmailMessage

class Index(generic.ListView):
    
    template_name = 'index.html'
    
    queryset = ScheduleRegister.objects.order_by('-date')

class Index2(generic.ListView):

    template_name = 'index.html'

    queryset = ScheduleRegister.objects.order_by('date')

@method_decorator(login_required, name='dispatch')
class CreateSchedule(generic.CreateView):
    form_class = ScheduleRegisterForm
    
    template_name = 'schedule_register.html'
    
    success_url = reverse_lazy('schedule:done')
        
    def form_valid(self, form):
        postdata = form.save(commit=False)
        
        postdata.user = self.request.user
        
        postdata.save()
        
        return super().form_valid(form)

class Done(generic.TemplateView):
    
    template_name = 'success_register.html'

class Detail(generic.DetailView):

    template_name = 'detail.html'

    model = ScheduleRegister

class Delete(generic.DeleteView):

    template_name = 'delete.html'

    model = ScheduleRegister

    success_url = reverse_lazy('schedule:index')

    def delete(self, request, *args, **kwargs):

        return super().delete(request, *args, **kwargs)

class Contact(generic.FormView):
    
    template_name = 'contact.html'

    form_class = ContactForm

    success_url = reverse_lazy('schedule:contact')

    def form_valid(self, form):

        name = form.cleaned_data['name']

        email = form.cleaned_data['email']

        message = form.cleaned_data['message']

        title = form.cleaned_data['title']

        subject = 'お問い合わせ: {}'.format(title)

        message = \
            '送信者名:{0}\nメールアドレス:{1}\nタイトル:{2}\nメッセージ:\n{3}'\
                .format(name, email, title, message)
        
        from_email = 'admin@example.com'

        to_list = ['admin@example.com']

        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        message.send()
        messages.success(
            self.request,
            'お問い合わせを受け付けました')
        
        return super().form_valid(form)

accounts/templates/login.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);


.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #4CAF50;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #76b852; /* fallback for old browsers */
  background: rgb(141,194,111);
  background: linear-gradient(90deg, rgba(141,194,111,1) 0%, rgba(118,184,82,1) 50%);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;  

}
</style>
<body>
    {% if form.errors %}
      <p style="color: red;">ユーザー名とパスワードが一致しません</p>
    {% endif %}
<form method="post">
    {% csrf_token %}
    <div class="login-page">
        <div class="form">
        <form class="login-form">
            <input type="text" placeholder="username" name="username" maxlength="150" autocapitalize="none" autocomplete="username" required autofocus/>
            <input type="password" placeholder="password" name="password" autocomplete="current-password" required autofocus/>

            <input class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">
            <p class="message">未登録の方 <a href="{% url 'accounts:signup' %}">アカウントを作成</a></p>
            <input name="next" type="hidden" value="{% url 'schedule:index' %}">
        </form>
        </div>
    </div>
</form>

</body>
</html>

accounts/templates/logout.html
<style>
    .main {
        text-align: center;
    }

    .link  a {
        padding: 7px 13px;
        background: green;
        text-decoration: none;
        color: white;
        font-weight: bold;
        border-radius: 15px;
        transition: 0.5s;
    }
    .link a:hover {
        background-color: skyblue;
    }

    .link p {
        padding-bottom: 5px;
    }

    hr {
        color: skyblue;
        border: solid 2px;
    }

    .main h3 {
        font-weight: bold;
        
    }
</style>
<hr>
<div class="main">
    <h3><strong>ログアウトしました</strong></h3>
<div class="link">
    <p><a href="{% url 'schedule:index' %}">HOMEへ</a></p>
    <p><a href="{% url 'accounts:login' %}">Login画面へ</a></p>
    <p><a href="{% url 'accounts:signup' %}">アカウント新規作成</a></p>
</div>
</div>  
    <hr>

accounts/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock title %}
<body>
{% block contents %}
<h2 class="signuph2">アカウント登録</h2>

<form class="signup" method="post">
{% csrf_token %}
{% for field in form %}
<p class="form">
{{field.label_tag}}
{{field}}
{% if field.help_text %}
    <small style="color:grey">{{firld.help_text}}</small>
{% endif %}

    {% for error in field.errors %}
    <p style="color:red">{{error}}</p>
    {% endfor %}
</p>
{% endfor %}
<button type="submit">登録する</button>
</form>
<p class="return_home"><a href="{% url 'schedule:index' %}">登録をやめて、HOMEに戻る</a></p>

{% endblock contents %}
</body>
</html>

accounts/templates/signup_success.html
{% extends "base.html" %}
{% block title %}Success{% endblock title %}
{% block contents %}
    <h2>Success</h2>
    <p>登録が完了しました。</p>
{% endblock contents %}

schedule/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <a href="#"><img src="{% static 'img/schedule.png' %}" alt="schedule"></a>
      </header>
      
    {% if user.is_authenticated %}
      <nav>
        <a href="{% url 'schedule:index' %}">HOME</a>
        <a href="{% url 'schedule:register' %}">予定追加</a>
        <a href="{% url 'accounts:logout' %}">ログアウト</a>
        <a href="{% url 'schedule:contact' %}">コンタクト</a>
      </nav>
    {% else %}
      <nav>
        <a href="{% url 'schedule:index' %}">HOME</a>
        <a href="{% url 'accounts:signup' %}">新規登録</a>
        <a href="{% url 'accounts:login' %}">ログイン</a>
        <a href="{% url 'schedule:contact' %}">コンタクト</a>
      </nav>
    {% endif %}
    {% block contents %}{% endblock contents %}



</body>
</html>

    

schedule/templates/contact.html
{% extends "base.html" %}
{% block title %}Contact{% endblock title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% block contents %}
<style>

    form {
        max-width: 600px;
        margin: 0 auto;
    }

    .label {
        display: block;
        margin-bottom: 8px;
        width: auto;
        height: auto;
       
    }


    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #45a049;
    }

    .form_contact {
        text-align: center;
    }
</style>

<h1>Contact</h1>
{% if messages %}
<ul class="list-unstyled" style="list-style: none;">
{% for message in messages %}
<li {% if message.tags %} class="{{message.tags}}"{%endif%}>
    {{message}}
</li>
{% endfor %}
</ul>
{% endif %}
<div class="form_contact">
<form method="POST">
  {% csrf_token %}
    {% for field in form %}
    <div class="label">
        {{field.label_tag}}
    </div>
    <div class="field">
        {{field}}
    </div>
    {% endfor %}
    <br>
  <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
</form>
</div>
{% endblock contents %}

schedule/templates/delete.html
{% extends "base.html" %}
{% block title %}Delete{% endblock title %}
{% block contents %}
<form method="POST">
    <br>
    <p>削除してもいいですか？</p>
    {% csrf_token %}
    <button class="btn btn-primary my-2" type="submit">削除</button>
    <a href="{% url 'schedule:detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>

</form>     
{% endblock contents %}

schedule/templates/detail.html
{% extends "base.html" %}
{% block title %}Detail{% endblock title %}
{% block contents %}
<style>
    .detail {
        text-align: center;
    }

</style>
<div class="detail">
<h2>日付:{{object.date}}</h2>
<p>イベント:{{object.event}}</p>
<hr>
<p>場所:{{object.place}}</p>
</div>

{%if request.user == object.user%}
<form method="POST">
<button><a href="{% url 'schedule:delete' object.pk %}" class="btn btn-primary my-2">予定を削除</a></button>
</form>
{%endif%}
{% endblock contents %}

schedule/templates/index.html
{% extends "base.html" %}
{% load static %}
  <title>{% block title %}HOME{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<body>   
  {% block contents %}
 
  {% if user.is_authenticated %}
  <h1>予定表</h1>
<div class="sort">
  <button><a href="{% url 'schedule:index' %}">予定が遅い順</a></button>
  <button><a href="{% url 'schedule:index2' %}">予定が近い順</a></button>
</div>  
  <table>
    <thead>
      <tr>
        <th>日付</th>
        <th>イベント</th>
        <th>場所</th>
      </tr>
    </thead>
  {% for record in object_list %}
    <tbody>
      <tr>
        <td><button type="button" class="btn-sm btn-outline-secondary" onclick="location.href='{% url 'schedule:detail' record.pk %}'">{{record.date}}</button></td>
        <td>{{record.event}}</td>
        <td>{{record.place}}</td>
      </tr>
    </tbody>
    {% endfor %}
    </table>
    {% endif %}
    {% endblock contents %}
</body>
</html>

schedule/templates/schedule_register.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}
{% block contents %}
  
<form method="POST">
    {%csrf_token%}
    <table>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
        <tr>
            <th>イベント</th>
            <td>{{ form.event }}</td>
        </tr>
        <tr>
            <th>場所</th>
            <td>{{ form.place }}</td>
        </tr>
    </table>
    <hr>
    <button type="submit">予定を登録する</button>
  <a class="back" href="{% url 'schedule:index' %}">戻る</a>

</form>
{% endblock contents %}

schedule/templates/success_register.html
{% extends "base.html" %}
{% block title %}Success Register{% endblock title %}
{% block contents %}
<style>
    h1 {
        text-align: center;
        background-color: antiquewhite;
    }
    p {
        text-align: center;
        font-size: larger;
        font-weight: bold;
    }
</style>
<h1>登録が完了しました。</h1>
<p><a href="{% url 'schedule:register' %}">続けて予定を登録する</a></p>
<p><a href="{% url 'schedule:index' %}">HOMEに戻る</a></p>
{% endblock contents %}